apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./public-http-proxy.yaml
- ./private-http-proxy.yaml
- ./service.yaml
- ./service-account.yaml
- ./service-monitor.yaml

configMapGenerator:
- name: sample-app-env-variables
  env: ./env-vars.env

secretGenerator:
  - name: sample-app-basic-auth
    literals:
    - username=actuator
    - password=password

configurations:
  - ./service-monitor-config.yaml
