apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  type: ClusterIP
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: admin-port
    protocol: TCP
    port: 8081
    targetPort: 8081
