apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Set namespace in all files
namespace: dev

# Set image tags for deployment
images:
- name: alpine
  newTag: 365e93b
# Labels to set in all file
commonLabels:
  app.kubernetes.io/component: service
  app.kubernetes.io/created-by: argo-cd
  app.kubernetes.io/instance: sample-app-dev
  app.kubernetes.io/managed-by: argo-cd
  app.kubernetes.io/name: sample-app
  app.kubernetes.io/part-of: sample-platform

# Patches to apply to specific files
patches:
- path: deployment-patches.yaml
  target:
    group: apps
    kind: Deployment
    name: sample-app
    version: v1
- path: service-account-patches.yaml
  target:
    kind: ServiceAccount
    name: sample-app
    version: v1

# Files to use as bases for customization
resources:
- ../../../bases/app
